package main

import (
	"github.com/mterhar/golang-echo-realworld-example-app/db"
	"github.com/mterhar/golang-echo-realworld-example-app/handler"
	"github.com/mterhar/golang-echo-realworld-example-app/router"
	"github.com/mterhar/golang-echo-realworld-example-app/store"

	_ "github.com/mterhar/golang-echo-realworld-example-app/docs" // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger"                  // echo-swagger middleware

	beeline "github.com/honeycombio/beeline-go"
)

// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	beeline.Init(beeline.Config{
		WriteKey: "68f4ae9bbb6c0917c0e5f0b2a645fd19",
		Dataset:  "takehome-conduit",
		// STDOUT:   true,
	})
	defer beeline.Close()

	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewArticleStore(d)
	h := handler.NewHandler(us, as)
	h.Register(v1)
	r.Logger.Fatal(r.Start("127.0.0.1:8585"))
}
